# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LlcwWRxJ9OcjY1VND6DhuOS-wZEmTRKX
"""

from array import array

numero = int(input("dijite numeros que desea: "))
arreglo = []

for i in range(numero):
  arreglo.append (int(input("dijite sus digitos: ")))

print("su lista es",arreglo)
arreglo.reverse()
print("su lista invertida es",arreglo)



